const veggies = [
    { name: 'Artichoke', image: 'artichoke.jpg', description: 'A fiber-rich thistle vegetable known for its tender heart and earthy flavor.' },
    { name: 'Arugula', image: 'arugula.jpg', description: 'A peppery leafy green often used in salads, packed with antioxidants.' },
    { name: 'Asparagus', image: 'asparagus.jpg', description: 'A spring vegetable prized for its tender stalks and unique grassy taste.' },
    { name: 'Avocado', image: 'avocado.jpg', description: 'A creamy, nutrient-dense fruit rich in healthy fats and perfect for guacamole.' },
    { name: 'Bean Sprouts', image: 'bean_sprouts.jpg', description: 'Crunchy, refreshing sprouts often used in stir-fries and Asian dishes.' },
    { name: 'Beets', image: 'beets.jpg', description: 'A root vegetable with a sweet, earthy flavor and deep red color.' },
    { name: 'Bell Peppers', image: 'bell_peppers.jpg', description: 'Colorful and crisp, bell peppers are high in vitamin C and great raw or cooked.' },
    { name: 'Bok Choy', image: 'bok_choy.jpg', description: 'A type of Chinese cabbage with mild flavor and crunchy stalks, perfect for stir-fry.' },
    { name: 'Broccoli', image: 'broccoli.jpg', description: 'A cruciferous veggie known for its tree-like appearance and health benefits.' },
    { name: 'Brussels Sprouts', image: 'brussels_sprouts.jpg', description: 'Mini cabbages with a nutty flavor, especially delicious when roasted.' },
    { name: 'Butternut Squash', image: 'butternut_squash.jpg', description: 'A sweet, nutty winter squash great for roasting and soups.' },
    { name: 'Cabbage', image: 'cabbage.jpg', description: 'A versatile leafy vegetable used in slaws, stews, and fermented dishes.' },
    { name: 'Carrots', image: 'carrots.jpg', description: 'A crunchy, sweet root vegetable packed with beta-carotene and vitamins.' },
    { name: 'Cauliflower', image: 'cauliflower.jpg', description: 'A neutral-tasting veggie often used as a low-carb alternative to grains.' },
    { name: 'Celery', image: 'celery.jpg', description: 'Crisp and hydrating, celery is perfect for snacks, soups, and salads.' },
    { name: 'Chard', image: 'chard.jpg', description: 'A colorful leafy green loaded with vitamins and minerals, great sautéed.' },
    { name: 'Chayote', image: 'chayote.jpg', description: 'A mild-flavored squash commonly used in Latin American cuisine.' },
    { name: 'Chili Peppers', image: 'chili_peppers.jpg', description: 'Spicy and vibrant, chili peppers add heat and flavor to any dish.' },
    { name: 'Collard Greens', image: 'collard_greens.jpg', description: 'A hardy leafy green with a slightly bitter taste, often slow-cooked in Southern dishes.' },
    { name: 'Corn', image: 'corn.jpg', description: 'A sweet and starchy kernel vegetable enjoyed grilled, boiled, or popped.' },
    { name: 'Cucumber', image: 'cucumber.jpg', description: 'Cool and refreshing, cucumbers are a hydration-packed salad staple.' },
    { name: 'Daikon Radish', image: 'daikon_radish.jpg', description: 'A large white radish with a crisp texture and mild peppery flavor.' },
    { name: 'Dandelion Greens', image: 'dandelion_greens.jpg', description: 'Bitter greens full of antioxidants and often used in herbal medicine.' },
    { name: 'Edamame', image: 'edamame.jpg', description: 'Immature soybeans served in pods, popular as a protein-packed snack.' },
    { name: 'Eggplant', image: 'eggplant.jpg', description: 'A glossy purple fruit often grilled, roasted, or used in Mediterranean cooking.' },
    { name: 'Endive', image: 'endive.jpg', description: 'A slightly bitter, crunchy green ideal for salads and appetizers.' },
    { name: 'Fennel', image: 'fennel.jpg', description: 'A licorice-flavored bulb and fronds often used in Italian and Mediterranean dishes.' },
    { name: 'Garlic', image: 'garlic.jpg', description: 'A pungent bulb with strong flavor and powerful health properties.' },
    { name: 'Ginger', image: 'ginger.jpg', description: 'A spicy root used in both cooking and herbal remedies.' },
    { name: 'Green Beans', image: 'green_beans.jpg', description: 'Tender pods that are sweet and crunchy when steamed or sautéed.' },
    { name: 'Jicama', image: 'jicama.jpg', description: 'A sweet, crunchy root veggie eaten raw or tossed into slaws.' },
    { name: 'Kale', image: 'kale.jpg', description: 'A nutrient powerhouse leafy green known for its dark, ruffled leaves.' },
    { name: 'Leeks', image: 'leeks.jpg', description: 'A mild onion-like vegetable used in soups and savory dishes.' },
    { name: 'Lettuce', image: 'lettuce.jpg', description: 'A classic leafy green base for salads and sandwiches.' },
    { name: 'Mushrooms', image: 'mushrooms.jpg', description: 'Fungi with umami flavor, great for grilling, sautéing, or roasting.' },
    { name: 'Mustard Greens', image: 'mustard_greens.jpg', description: 'Peppery greens often cooked or used in bold salads.' },
    { name: 'Okra', image: 'okra.jpg', description: 'A pod vegetable popular in Southern and Indian cooking, known for its slimy texture when stewed.' },
    { name: 'Onions', image: 'onions.jpg', description: 'A pungent and essential kitchen staple that adds depth to countless dishes.' },
    { name: 'Parsnips', image: 'parsnips.jpg', description: 'A sweet and starchy root veggie with a flavor similar to carrots.' },
    { name: 'Peas', image: 'peas.jpg', description: 'Sweet green spheres that are delicious fresh, frozen, or pureed.' },
    { name: 'Potatoes', image: 'potatoes.jpg', description: 'A starchy root vegetable with endless culinary uses — mashed, baked, or fried.' },
    { name: 'Pumpkin', image: 'pumpkin.jpg', description: 'A sweet, orange winter squash perfect for roasting or baking into pies.' },
    { name: 'Radish', image: 'radish.jpg', description: 'A spicy, crunchy root often used raw in salads and slaws.' },
    { name: 'Rutabaga', image: 'rutabaga.jpg', description: 'A mild-flavored root vegetable with a slightly sweet and nutty taste.' },
    { name: 'Scallions', image: 'scallions.jpg', description: 'Young onions with a mild bite, great raw or sautéed.' },
    { name: 'Shallots', image: 'shallots.jpg', description: 'Delicate, sweet onions perfect for sauces and vinaigrettes.' },
    { name: 'Snap Peas', image: 'snap_peas.jpg', description: 'Crisp, edible pods with a sweet bite — great for snacking or stir-fry.' },
    { name: 'Spinach', image: 'spinach.jpg', description: 'A tender leafy green full of iron and used fresh or cooked.' },
    { name: 'Sweet Potato', image: 'sweet_potato.jpg', description: 'A sweet and vibrant orange tuber packed with fiber and beta-carotene.' },
    { name: 'Swiss Chard', image: 'swiss_chard.jpg', description: 'A colorful, leafy green often sautéed with garlic and olive oil.' },
    { name: 'Tomato', image: 'tomato.jpg', description: 'A juicy, red fruit often used in sauces, salads, and sandwiches.' },
    { name: 'Turnip', image: 'turnip.jpg', description: 'A peppery white root veggie often roasted or added to stews.' },
    { name: 'Watercress', image: 'watercress.jpg', description: 'A peppery aquatic plant used in salads and soups.' },
    { name: 'Yam', image: 'yam.jpg', description: 'A starchy root with brown skin and white or orange flesh, often confused with sweet potatoes.' },
    { name: 'Zucchini', image: 'zucchini.jpg', description: 'A mild summer squash that’s great grilled, spiralized, or baked.' }
];
  
export default veggies;